"""typo fixed

Revision ID: 2bd88076e7cb
Revises: 97e21413463c
Create Date: 2022-05-13 12:16:06.777264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd88076e7cb'
down_revision = '97e21413463c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_index('ix_post_timespamp', table_name='post')
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.drop_column('post', 'timespamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timespamp', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.create_index('ix_post_timespamp', 'post', ['timespamp'], unique=False)
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
